export const ERROR_CATALOG = {
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_INVALID_OTP: 'AUTH_INVALID_OTP',
  AUTH_OTP_RATE_LIMITED: 'AUTH_OTP_RATE_LIMITED',
  WALLET_ALREADY_LINKED: 'WALLET_ALREADY_LINKED',
  WALLET_RECOVERY_PENDING: 'WALLET_RECOVERY_PENDING',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CATALOG)[keyof typeof ERROR_CATALOG];
