import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialFullSchemaV21777398992108 implements MigrationInterface {
    name = 'InitialFullSchemaV21777398992108'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "system_logs" DROP CONSTRAINT "system_logs_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" DROP CONSTRAINT "wallet_recovery_requests_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" DROP CONSTRAINT "wallet_recovery_requests_approved_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "wallets_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "wallet_secrets" DROP CONSTRAINT "wallet_secrets_wallet_address_fkey"`);
        await queryRunner.query(`CREATE TABLE "auth_identities" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "provider" character varying(50) NOT NULL, "provider_id" character varying(255) NOT NULL, "auth_level" character varying(50), "last_verified_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_c06a980d83c42611d27a294e55" UNIQUE ("user_id"), CONSTRAINT "PK_63a29aebcddd09448dbeee4666b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_sessions" ("id" character varying NOT NULL, "user_id" integer NOT NULL, "provider_session_id" character varying(255), "ip_address" character varying(45), "user_agent" text, "expires_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e93e031a5fed190d4789b6bfd83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "land_records" ("id" SERIAL NOT NULL, "owner_id" integer NOT NULL, "address" text NOT NULL, "area" numeric(20,2) NOT NULL, "gps_coordinates" text, "is_frozen" boolean NOT NULL DEFAULT false, "status" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a2aadf773895679c4b060543bad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "land_record_versions" ("id" SERIAL NOT NULL, "record_id" integer NOT NULL, "editor_id" integer NOT NULL, "old_area" numeric(20,2), "new_area" numeric(20,2), "old_gps_coordinates" text, "new_gps_coordinates" text, "edit_reason" text, "version_number" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_740cbda55879f1b4701d30582c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "land_files" ("id" SERIAL NOT NULL, "record_id" integer NOT NULL, "file_name" character varying(255) NOT NULL, "file_type" character varying(50) NOT NULL, "ipfs_cid" character varying(255) NOT NULL, "uploaded_by" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a0ec52e20157fc853c23944a67b" UNIQUE ("ipfs_cid"), CONSTRAINT "PK_a875b302b474ab6d0d7d09d8a22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "blockchain_logs" ("tx_hash" character varying NOT NULL, "action_type" character varying(100) NOT NULL, "gas_fee" numeric(20,10), "status" character varying(50) NOT NULL, "timestamp" TIMESTAMP NOT NULL, CONSTRAINT "PK_e418bbdf8e9477103a259857294" PRIMARY KEY ("tx_hash"))`);
        await queryRunner.query(`CREATE TABLE "smart_contracts" ("contract_address" character varying NOT NULL, "name" character varying(255) NOT NULL, "abi" text NOT NULL, "version" character varying(50), "status" character varying(50) NOT NULL DEFAULT 'Active', "deployed_at" TIMESTAMP, CONSTRAINT "PK_153e806e989a8f2b456ea38a893" PRIMARY KEY ("contract_address"))`);
        await queryRunner.query(`CREATE TABLE "land_nfts" ("token_id" character varying NOT NULL, "record_id" integer NOT NULL, "contract_address" character varying NOT NULL, "owner_wallet" character varying NOT NULL, "metadata_uri" text NOT NULL, "qr_code" character varying(255), "mint_tx_hash" character varying, "status" character varying(50) NOT NULL DEFAULT 'Normal', "mint_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_056b2afc4a56183b480afb2d1d3" UNIQUE ("qr_code"), CONSTRAINT "REL_97d2193636e53d6e62a655a67a" UNIQUE ("record_id"), CONSTRAINT "REL_32b3ff383f2494dca815274a84" UNIQUE ("mint_tx_hash"), CONSTRAINT "PK_695f6ede6a2943b517110a80f3a" PRIMARY KEY ("token_id"))`);
        await queryRunner.query(`CREATE TABLE "cached_provenance_logs" ("id" SERIAL NOT NULL, "token_id" character varying NOT NULL, "event_type" character varying(100) NOT NULL, "event_data" text NOT NULL, "tx_hash" character varying NOT NULL, "block_number" integer NOT NULL, "cached_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8e825b67014a8e3d107171748ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "approval_requests" ("id" SERIAL NOT NULL, "record_id" integer NOT NULL, "request_type" character varying(100) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'Pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_484806bb8ff331b851fc75973c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "signatures" ("id" SERIAL NOT NULL, "request_id" integer NOT NULL, "user_id" integer NOT NULL, "decision" character varying(50) NOT NULL, "reason" text, "sign_tx_hash" character varying(255), "signed_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f56eb3cd344ce7f9ae28ce814eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" SERIAL NOT NULL, "token_id" character varying NOT NULL, "seller_id" integer NOT NULL, "buyer_id" integer NOT NULL, "certifier_id" integer, "contract_price" numeric(20,2) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'Draft', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "completed_at" TIMESTAMP, CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "taxes_fees" ("id" SERIAL NOT NULL, "transaction_id" integer NOT NULL, "tax_type" character varying(100) NOT NULL, "amount" numeric(20,2) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'Unpaid', "calculated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7a471484931fe5fc8c058728fec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "receipts" ("id" SERIAL NOT NULL, "tax_id" integer NOT NULL, "payment_method" character varying(100), "blockchain_tx_hash" character varying(255), "paid_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_d24a8df235f06f981959d52f87" UNIQUE ("tax_id"), CONSTRAINT "PK_5e8182d7c29e023da6e1ff33bfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "planning_zones" ("id" SERIAL NOT NULL, "zone_name" character varying(255) NOT NULL, "description" text, "polygon_coordinates" text, "status" character varying(50), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d5d04aa15a0099c007a8bbcf47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "land_planning_map" ("record_id" integer NOT NULL, "zone_id" integer NOT NULL, "status" character varying(50) NOT NULL, CONSTRAINT "PK_d10818b852eb9f26f7979b6d90f" PRIMARY KEY ("record_id", "zone_id"))`);
        await queryRunner.query(`CREATE TABLE "disputes" ("id" SERIAL NOT NULL, "token_id" character varying NOT NULL, "claimant_id" integer NOT NULL, "description" text NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'Pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "resolved_at" TIMESTAMP, CONSTRAINT "PK_3c97580d01c1a4b0b345c42a107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mortgages" ("id" SERIAL NOT NULL, "token_id" character varying NOT NULL, "bank_name" character varying(255) NOT NULL, "mortgage_amount" numeric(20,2) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'Active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "released_at" TIMESTAMP, CONSTRAINT "PK_5ca97f78106db808696b2dc2084" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fraud_reports" ("id" SERIAL NOT NULL, "reporter_id" integer NOT NULL, "token_id" character varying NOT NULL, "reason" text NOT NULL, "evidence_images" text, "status" character varying(50) NOT NULL DEFAULT 'Pending', "reviewed_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6577bdf0d3a126b7560b36f2a80" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "system_configs" ("config_key" character varying NOT NULL, "config_value" text NOT NULL, "description" text, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8430d4ebdc1faef3d3eeef36e87" PRIMARY KEY ("config_key"))`);
        await queryRunner.query(`CREATE TABLE "system_config_audits" ("id" SERIAL NOT NULL, "config_key" character varying NOT NULL, "editor_id" integer NOT NULL, "old_value" text, "new_value" text, "changed_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e3897c2ecc59db18b65c647e9dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "title" character varying(255) NOT NULL, "content" text NOT NULL, "type" character varying(50) NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_logs" ADD CONSTRAINT "FK_a572427d16b851f8d9f1e8e7a36" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" ADD CONSTRAINT "FK_4ff36236fac4520dde02cd94195" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" ADD CONSTRAINT "FK_9ed6451f5f52b8ed6c1e182bd85" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_secrets" ADD CONSTRAINT "FK_59b02004a721ea4d8616fffd54b" FOREIGN KEY ("wallet_address") REFERENCES "wallets"("wallet_address") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_identities" ADD CONSTRAINT "FK_c06a980d83c42611d27a294e55c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land_records" ADD CONSTRAINT "FK_ef1078bba95f9d062c23dfdf4f4" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land_record_versions" ADD CONSTRAINT "FK_62faa96aff3dced9ff5cf07f521" FOREIGN KEY ("record_id") REFERENCES "land_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land_record_versions" ADD CONSTRAINT "FK_d5151c042807ba58b058d6810de" FOREIGN KEY ("editor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land_files" ADD CONSTRAINT "FK_d6c156f4bde16bb48764632892e" FOREIGN KEY ("record_id") REFERENCES "land_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land_files" ADD CONSTRAINT "FK_3875d3a0dedd2a8915e237af299" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land_nfts" ADD CONSTRAINT "FK_97d2193636e53d6e62a655a67a1" FOREIGN KEY ("record_id") REFERENCES "land_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land_nfts" ADD CONSTRAINT "FK_468e742404bcd38ce8514407c22" FOREIGN KEY ("contract_address") REFERENCES "smart_contracts"("contract_address") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land_nfts" ADD CONSTRAINT "FK_fb35ea3824c78a8fa38954ffff8" FOREIGN KEY ("owner_wallet") REFERENCES "wallets"("wallet_address") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land_nfts" ADD CONSTRAINT "FK_32b3ff383f2494dca815274a841" FOREIGN KEY ("mint_tx_hash") REFERENCES "blockchain_logs"("tx_hash") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cached_provenance_logs" ADD CONSTRAINT "FK_d89ab68ef3cd9f792bc38135a60" FOREIGN KEY ("token_id") REFERENCES "land_nfts"("token_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cached_provenance_logs" ADD CONSTRAINT "FK_b696a35243eda28cce8a390774e" FOREIGN KEY ("tx_hash") REFERENCES "blockchain_logs"("tx_hash") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_requests" ADD CONSTRAINT "FK_7c2bb4c5fb17d4456936b35c494" FOREIGN KEY ("record_id") REFERENCES "land_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signatures" ADD CONSTRAINT "FK_fa876265213fc7eb7404c637400" FOREIGN KEY ("request_id") REFERENCES "approval_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signatures" ADD CONSTRAINT "FK_c93e294b75e34b850a599a51e2c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_e7c567e9200942c30954f0933d5" FOREIGN KEY ("token_id") REFERENCES "land_nfts"("token_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_214e8e26a3bc13250ef55e9a1af" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_8c9b301d18f4ed8cacff33664c6" FOREIGN KEY ("buyer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_2bcda45d940b587a7a9c1136aab" FOREIGN KEY ("certifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taxes_fees" ADD CONSTRAINT "FK_ae8f87a8ac0ebd51174d9628017" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "FK_d24a8df235f06f981959d52f87d" FOREIGN KEY ("tax_id") REFERENCES "taxes_fees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land_planning_map" ADD CONSTRAINT "FK_7cb55c33ed31920d8b5b58e3af3" FOREIGN KEY ("record_id") REFERENCES "land_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "land_planning_map" ADD CONSTRAINT "FK_532a3985e803abc1c9477afd54b" FOREIGN KEY ("zone_id") REFERENCES "planning_zones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_0b02a4b147c53a206f6582ffd3a" FOREIGN KEY ("token_id") REFERENCES "land_nfts"("token_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_eb1b4f3048deddcadd44f06e26f" FOREIGN KEY ("claimant_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mortgages" ADD CONSTRAINT "FK_776b849b97ad68fc06202260451" FOREIGN KEY ("token_id") REFERENCES "land_nfts"("token_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fraud_reports" ADD CONSTRAINT "FK_297c178f95c26c2679e50647ae2" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fraud_reports" ADD CONSTRAINT "FK_bcc1b3d6420365903fdbd5afaa2" FOREIGN KEY ("token_id") REFERENCES "land_nfts"("token_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fraud_reports" ADD CONSTRAINT "FK_feadfd77a77f837e3c1767eacdb" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_config_audits" ADD CONSTRAINT "FK_7ef66838d67644caee5312c8de1" FOREIGN KEY ("config_key") REFERENCES "system_configs"("config_key") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_config_audits" ADD CONSTRAINT "FK_95e5f076d6e1004191069c91222" FOREIGN KEY ("editor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "system_config_audits" DROP CONSTRAINT "FK_95e5f076d6e1004191069c91222"`);
        await queryRunner.query(`ALTER TABLE "system_config_audits" DROP CONSTRAINT "FK_7ef66838d67644caee5312c8de1"`);
        await queryRunner.query(`ALTER TABLE "fraud_reports" DROP CONSTRAINT "FK_feadfd77a77f837e3c1767eacdb"`);
        await queryRunner.query(`ALTER TABLE "fraud_reports" DROP CONSTRAINT "FK_bcc1b3d6420365903fdbd5afaa2"`);
        await queryRunner.query(`ALTER TABLE "fraud_reports" DROP CONSTRAINT "FK_297c178f95c26c2679e50647ae2"`);
        await queryRunner.query(`ALTER TABLE "mortgages" DROP CONSTRAINT "FK_776b849b97ad68fc06202260451"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_eb1b4f3048deddcadd44f06e26f"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_0b02a4b147c53a206f6582ffd3a"`);
        await queryRunner.query(`ALTER TABLE "land_planning_map" DROP CONSTRAINT "FK_532a3985e803abc1c9477afd54b"`);
        await queryRunner.query(`ALTER TABLE "land_planning_map" DROP CONSTRAINT "FK_7cb55c33ed31920d8b5b58e3af3"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "FK_d24a8df235f06f981959d52f87d"`);
        await queryRunner.query(`ALTER TABLE "taxes_fees" DROP CONSTRAINT "FK_ae8f87a8ac0ebd51174d9628017"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_2bcda45d940b587a7a9c1136aab"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_8c9b301d18f4ed8cacff33664c6"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_214e8e26a3bc13250ef55e9a1af"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_e7c567e9200942c30954f0933d5"`);
        await queryRunner.query(`ALTER TABLE "signatures" DROP CONSTRAINT "FK_c93e294b75e34b850a599a51e2c"`);
        await queryRunner.query(`ALTER TABLE "signatures" DROP CONSTRAINT "FK_fa876265213fc7eb7404c637400"`);
        await queryRunner.query(`ALTER TABLE "approval_requests" DROP CONSTRAINT "FK_7c2bb4c5fb17d4456936b35c494"`);
        await queryRunner.query(`ALTER TABLE "cached_provenance_logs" DROP CONSTRAINT "FK_b696a35243eda28cce8a390774e"`);
        await queryRunner.query(`ALTER TABLE "cached_provenance_logs" DROP CONSTRAINT "FK_d89ab68ef3cd9f792bc38135a60"`);
        await queryRunner.query(`ALTER TABLE "land_nfts" DROP CONSTRAINT "FK_32b3ff383f2494dca815274a841"`);
        await queryRunner.query(`ALTER TABLE "land_nfts" DROP CONSTRAINT "FK_fb35ea3824c78a8fa38954ffff8"`);
        await queryRunner.query(`ALTER TABLE "land_nfts" DROP CONSTRAINT "FK_468e742404bcd38ce8514407c22"`);
        await queryRunner.query(`ALTER TABLE "land_nfts" DROP CONSTRAINT "FK_97d2193636e53d6e62a655a67a1"`);
        await queryRunner.query(`ALTER TABLE "land_files" DROP CONSTRAINT "FK_3875d3a0dedd2a8915e237af299"`);
        await queryRunner.query(`ALTER TABLE "land_files" DROP CONSTRAINT "FK_d6c156f4bde16bb48764632892e"`);
        await queryRunner.query(`ALTER TABLE "land_record_versions" DROP CONSTRAINT "FK_d5151c042807ba58b058d6810de"`);
        await queryRunner.query(`ALTER TABLE "land_record_versions" DROP CONSTRAINT "FK_62faa96aff3dced9ff5cf07f521"`);
        await queryRunner.query(`ALTER TABLE "land_records" DROP CONSTRAINT "FK_ef1078bba95f9d062c23dfdf4f4"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_e9658e959c490b0a634dfc54783"`);
        await queryRunner.query(`ALTER TABLE "auth_identities" DROP CONSTRAINT "FK_c06a980d83c42611d27a294e55c"`);
        await queryRunner.query(`ALTER TABLE "wallet_secrets" DROP CONSTRAINT "FK_59b02004a721ea4d8616fffd54b"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" DROP CONSTRAINT "FK_9ed6451f5f52b8ed6c1e182bd85"`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" DROP CONSTRAINT "FK_4ff36236fac4520dde02cd94195"`);
        await queryRunner.query(`ALTER TABLE "system_logs" DROP CONSTRAINT "FK_a572427d16b851f8d9f1e8e7a36"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "PK_bca8b30f6524979bf57a2b2c1be"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP COLUMN "wallet_address"`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD "wallet_address" character varying(42) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "wallets_pkey" PRIMARY KEY ("wallet_address")`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" DROP COLUMN "new_wallet_address"`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" ADD "new_wallet_address" character varying(42) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" DROP COLUMN "old_wallet_address"`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" ADD "old_wallet_address" character varying(42) NOT NULL`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "system_config_audits"`);
        await queryRunner.query(`DROP TABLE "system_configs"`);
        await queryRunner.query(`DROP TABLE "fraud_reports"`);
        await queryRunner.query(`DROP TABLE "mortgages"`);
        await queryRunner.query(`DROP TABLE "disputes"`);
        await queryRunner.query(`DROP TABLE "land_planning_map"`);
        await queryRunner.query(`DROP TABLE "planning_zones"`);
        await queryRunner.query(`DROP TABLE "receipts"`);
        await queryRunner.query(`DROP TABLE "taxes_fees"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TABLE "signatures"`);
        await queryRunner.query(`DROP TABLE "approval_requests"`);
        await queryRunner.query(`DROP TABLE "cached_provenance_logs"`);
        await queryRunner.query(`DROP TABLE "land_nfts"`);
        await queryRunner.query(`DROP TABLE "smart_contracts"`);
        await queryRunner.query(`DROP TABLE "blockchain_logs"`);
        await queryRunner.query(`DROP TABLE "land_files"`);
        await queryRunner.query(`DROP TABLE "land_record_versions"`);
        await queryRunner.query(`DROP TABLE "land_records"`);
        await queryRunner.query(`DROP TABLE "user_sessions"`);
        await queryRunner.query(`DROP TABLE "auth_identities"`);
        await queryRunner.query(`ALTER TABLE "wallet_secrets" ADD CONSTRAINT "wallet_secrets_wallet_address_fkey" FOREIGN KEY ("wallet_address") REFERENCES "wallets"("wallet_address") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "wallets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" ADD CONSTRAINT "wallet_recovery_requests_approved_by_fkey" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_recovery_requests" ADD CONSTRAINT "wallet_recovery_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_logs" ADD CONSTRAINT "system_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
