/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LandRegistryInterface extends Interface {
  getFunction(nameOrSignature: "landOwners" | "registerLand"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LandRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "landOwners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerLand",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "landOwners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerLand",
    data: BytesLike
  ): Result;
}

export namespace LandRegisteredEvent {
  export type InputTuple = [landId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [landId: bigint, owner: string];
  export interface OutputObject {
    landId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LandRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LandRegistry;
  waitForDeployment(): Promise<this>;

  interface: LandRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  landOwners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  registerLand: TypedContractMethod<
    [landId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "landOwners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registerLand"
  ): TypedContractMethod<[landId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "LandRegistered"
  ): TypedContractEvent<
    LandRegisteredEvent.InputTuple,
    LandRegisteredEvent.OutputTuple,
    LandRegisteredEvent.OutputObject
  >;

  filters: {
    "LandRegistered(uint256,address)": TypedContractEvent<
      LandRegisteredEvent.InputTuple,
      LandRegisteredEvent.OutputTuple,
      LandRegisteredEvent.OutputObject
    >;
    LandRegistered: TypedContractEvent<
      LandRegisteredEvent.InputTuple,
      LandRegisteredEvent.OutputTuple,
      LandRegisteredEvent.OutputObject
    >;
  };
}
