/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { LandNFT, LandNFTInterface } from "../LandNFT";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "NFTMinted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610144806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806318160ddd1461003b5780636a62784214610056575b600080fd5b61004460005481565b60405190815260200160405180910390f35b6100696100643660046100b7565b61006b565b005b60008054908061007a836100e7565b9091555050600080546040516001600160a01b038416927f0176f203df400d7bd5f1b1c9ef36c16709bf3b5d9fd35f000a6bae32393f66c391a350565b6000602082840312156100c957600080fd5b81356001600160a01b03811681146100e057600080fd5b9392505050565b60006001820161010757634e487b7160e01b600052601160045260246000fd5b506001019056fea26469706673582212206da1797c9d274ecc93040978b092544406701e54251d264aa7acc99f6982fcf764736f6c63430008180033";

type LandNFTConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LandNFTConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LandNFT__factory extends ContractFactory {
  constructor(...args: LandNFTConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      LandNFT & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LandNFT__factory {
    return super.connect(runner) as LandNFT__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LandNFTInterface {
    return new Interface(_abi) as LandNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): LandNFT {
    return new Contract(address, _abi, runner) as unknown as LandNFT;
  }
}
