/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { LandRegistry, LandRegistryInterface } from "../LandRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "landId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "LandRegistered",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "landOwners",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "landId",
        type: "uint256",
      },
    ],
    name: "registerLand",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061019c806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80631a0f76b11461003b578063baadce9014610080575b600080fd5b61006461004936600461014d565b6000602081905290815260409020546001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b61009361008e36600461014d565b610095565b005b6000818152602081905260409020546001600160a01b0316156100fe5760405162461bcd60e51b815260206004820152601760248201527f4c616e6420616c72656164792072656769737465726564000000000000000000604482015260640160405180910390fd5b60008181526020819052604080822080546001600160a01b031916339081179091559051909183917fcb4990052f95f6057496d19524f6c3163f50af9f33f2c15b092928e03414323e9190a350565b60006020828403121561015f57600080fd5b503591905056fea26469706673582212204d90f305c2f57b7107f94eb078e64f519ae64092abcb2e0194d04de9b75cd6a164736f6c63430008180033";

type LandRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LandRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LandRegistry__factory extends ContractFactory {
  constructor(...args: LandRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      LandRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LandRegistry__factory {
    return super.connect(runner) as LandRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LandRegistryInterface {
    return new Interface(_abi) as LandRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): LandRegistry {
    return new Contract(address, _abi, runner) as unknown as LandRegistry;
  }
}
